### ISSUE TITLE
Clicking on search result does not work

### ISSUE THREAD

**Issue by jonathan-wiens** [smallbusinesshero/dds-wvv-frontend#23]
When I search for "Neu" and click on "Neukölln" nothing happens. It should instead fill "Neukölln" into the search bar and start searching (without having to click on "search"

![image](https://user-images.githubusercontent.com/1003491/77254047-dc7b1180-6c5e-11ea-8cde-84b39c816636.png)

**Comment by Kruspe** [comment]
This works on my machine and on the deployed version as well.

**Comment by connorlanigan** [comment]
This does not work for me on the deployed version (Chrome)
