### ISSUE TITLE
Technical basement - Adapt CSS to use material ui theme

### ISSUE THREAD

**Issue by haugthom** [smallbusinesshero/dds-wvv-frontend#34]
Each CSS should use colors from material ui theme. Currently color values are duplicated.
Also p tags, or h* tags should be replaced by Typography components from material ui. Goal is that the theming works in a right way.

**Comment by jonathan-wiens** [comment]
Check with @haugthom and @Lebski before working on this (https://github.com/smallbusinesshero/dds-wvv-frontend/issues/40)
