### ISSUE TITLE
Adapt search field label and placeholder 

### ISSUE THREAD

**Issue by cnasenberg** [smallbusinesshero/dds-wvv-frontend#39]
### Acceptance Criteria
- Search box has label 'Nachbarschaft', instead of 'Ort'. 
- Placeholder text inside the search box is 'z.B. Körtekiez', instead of 'Wähle einen Ort'. 

### Info 
We want to prevent users from entering their zip code by mistake.

**Comment by haugthom** [comment]
From where do we get all this "Körtkiez" names, ist there a database? I think this will not scale? I would like build something which works everywhere, maybe also in another country if they want to adapt our solution.

I would recommend to use address and radius search?

**Comment by cnasenberg** [comment]
It's a hard coded list based on some of my suggestions. We were under time pressure, had not time to implement a neighborhood endpoint or so. Nope, that does not scale at all. :D 

Yeah, we should offer people to enter their zip code or full address in any case, or just use their geo location. 

I would like to try and keep a selection of small 'cultural' neighborhoods for the larger cities. Those might not be in maps, maybe we can find a way to offer the neighborhood selection only when a person is in a larger city (geo location, again). 

A 'city' branding for the page, based on geo location would also be nice. Make it feel a bit more... local.

**Comment by haugthom** [comment]
Would this be a 1 to n mapping? zipcode (1) to neighborhood(n) ?
So then i think we should offer the zipcode search and a feature could be to recommend a neighbourhood" based on the zipcode. Because then it would be easy to treat them as "tags" for a zipcode.

**Comment by schugnic** [comment]
For  transparency I proposed a technical concept how we can handle this issue.
@haugthom 

https://github.com/Diconium-WirVsVirus/dds-wvv-backend/issues/24

At the moment i feel like there is no concept at all.
And I think most of the 'cultural' neighborhoods could also be in maps or define as geo shape in elasticsearch. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html

**Comment by connorlanigan** [comment]
If I understand the result of the merge request https://github.com/smallbusinesshero/dds-wvv-backend/pull/28 correctly, then we now have a freetext location search that returns suitable stores. Is that correct, @PapaBravo ?

**Comment by cnasenberg** [comment]
@connorlanigan you are right. We do have free text location now, so we do support 'location'. Therefore we can close this story, won't fix.
