### ISSUE TITLE
Restructure Frontend

### ISSUE THREAD

**Issue by Lebski** [smallbusinesshero/dds-wvv-frontend#40]
`Open for discussion `

I think it would be good if we structured the front end more sustainably. 

- Differentiation of sites and components 
- Everything is decoupled in a component (menu, footer, etc.) 
- Material UI with JSS 
- State with redux and inject stat through containers

I'd be open to take care of that, just give me green light for individual issues

**Comment by jonathan-wiens** [comment]
@haugthom what is your opinion? I think it makes sense

**Comment by haugthom** [comment]
yes it includes https://github.com/Diconium-WirVsVirus/dds-wvv-frontend/issues/34

**Comment by haugthom** [comment]
Maybe we can create our "theme" with this generator? https://cimdalli.github.io/mui-theme-generator/ Could be done together with ux/design team?

**Comment by haugthom** [comment]
https://www.npmtrends.com/material-ui-vs-antd 

We could also use Ant Design: https://ant.design/

**Comment by Lebski** [comment]
I would go for material ui. It's so easy and so broadly used. Everyone in react space knows it and literally everything from material design guide is already coded. 
They have even components like maps api already prepared. And it integrates with everything.

**Comment by haugthom** [comment]
Before we continue with that, i would recommend to re-setup the project with nextjs:
https://nextjs.org/ - We used this already in projects with success.

**Comment by Lebski** [comment]
Would be way better for SEO 👍

**Comment by jonathan-wiens** [comment]
Great. This seems like a greater task that should be done before we start with other things.

**Comment by Lebski** [comment]
Is it possible to structure the project as normal react.js project and later introduce next.js? 
If yes I'd start over the weekend and @haugthom jumps in and introduces next.js...
