### ISSUE TITLE
Add sonarcloud status badge to readme

### ISSUE THREAD

**Issue by jonathan-wiens** [smallbusinesshero/dds-wvv-frontend#47]
We want to see the current sonarcloud report on the README page. Please add the following badge with the correct Sonarcloud project URL for the frontend and backend repo like this:

`[![Sonarcloud Status](https://sonarcloud.io/api/project_badges/measure?project=com.lapots.breed.judge:judge-rule-engine&metric=alert_status)](https://sonarcloud.io/dashboard?id=com.lapots.breed.judge:judge-rule-engine)`

**Comment by jonathan-wiens** [comment]
Found the right URL string :) I'll do this quickly

**Comment by jonathan-wiens** [comment]
Opened PR https://github.com/smallbusinesshero/dds-wvv-frontend/pull/46

**Comment by haugthom** [comment]
merged
