### ISSUE TITLE
Bug: Black overlay darkens stores in search view

### ISSUE THREAD

**Issue by cnasenberg** [smallbusinesshero/dds-wvv-frontend#55]
When you hover your cursor over a store in the search view, it blackens. It's almost not readable. 

Happens on mobile (Firefox, Chrome) and desktop (Safari). See screenshot: https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fpbs.twimg.com%2Fmedia%2FEUVZXG6WoAA9DwH.jpg

**Comment by haugthom** [comment]
Pull Request created with an fix :)

**Comment by cnasenberg** [comment]
@haugthom, unfortunately, this is not solved yet, the tiles are still black. Please have another look.

**Comment by haugthom** [comment]
Did you check on develop?

**Comment by cnasenberg** [comment]
Ha, we need a definition of done. From my point of view, if I cannot see it in our live application, it's not done yet. To my knowledge, there is no intermediate approval environment/process. This means that our current process does not end with a merge to deployment. Instead, we as a team are all responsible for making sure that our changes/fixes are deployed to master in a coordinated way before we close an issue. Let's talk about it again, if you see major flaws here. @connorlanigan and @haugthom

**Comment by cnasenberg** [comment]
Thank you for deploying, by the way, it's fixed now! Nice!
