### ISSUE TITLE
Add TLS certificate to website

### ISSUE THREAD

**Issue by connorlanigan** [smallbusinesshero/dds-wvv-frontend#57]
The website is currently running on plain HTTP. We should add a TLS certificate to it and redirect all requests to HTTPS.

A possible, low-cost solution is switching to a provider that provides TLS certificates automatically.

**Comment by haugthom** [comment]
Hi @connorlanigan,

i added a pull request to force https on server side.
To really check it on heroku, we need to deploy it.

I tested it locally as far i could.
Maybe you can have a look.

Best
Thomas

**Comment by haugthom** [comment]
It is live and deployed including the redirect from non-https to https.
