### ISSUE TITLE
Store page (product map)

### ISSUE THREAD

**Issue by jonathan-wiens** [smallbusinesshero/dds-wvv-frontend#6]
**Story**
As a customer
I want to have more information about the products a small business offers
so I can buy the products when I contact the business owner

**Acceptance Criteria**
- A map of are products (as card elements) is shown to the customer
- A product tile should be the image of the product with the title of the product and price
- Nice to have: if you click / tap on the tile, it expands and shows the description

**Technical hints**
- The route should for this page is: /store?id=1
- See https://docs.google.com/document/d/1v9D8XToGbJJ3emQhzN3zmIBLR67XFM6mi1h2_yaorO4/edit#heading=h.o5rkwua83gl9 for API endpoint / data model for the products

**Comment by joetjengerdes** [comment]
Relates to feature: https://github.com/Diconium-WirVsVirus/dds-wvv-frontend/issues/4
