### ISSUE TITLE
Make search hints useful

### ISSUE THREAD

**Issue by cnasenberg** [smallbusinesshero/dds-wvv-frontend#93]
The search currently says 'Ort' and 'Wähle einen Ort...'. It is not clear what the user should enter. 

Acceptance Criteria 
- The search field label says 'Adresse oder Stadtviertel'. 
- The hint inside the search field says 'z.B. Donaustraße, Berlin'

**Comment by haugthom** [comment]
Please check my merge request

**Comment by jonathan-wiens** [comment]
Merged and done
